### PR TITLE
Fix issue with deserialization of error response.

### PR DESCRIPTION
**Pull request by SilasKenneth**

### CODE REVIEW

**Review by andrueastman — APPROVED** [review]

**Review by Ndiritu — APPROVED** [review]

**Comment by baywet** [comment]
@SilasKenneth can you rebase and add an entry to the changelog now that it's present please?

**Comment by SilasKenneth** [comment]
> @SilasKenneth can you rebase and add an entry to the changelog now that it's present please?

Hi @baywet, There is already an entry in the change log.

**Comment by baywet** [comment]
@SilasKenneth right, that's the entry for #82 that's missing then, and an entry for the new version

**Review by Ndiritu — APPROVED** [review]

**Comment by SilasKenneth** [comment]
> @SilasKenneth right, that's the entry for #82 that's missing then, and an entry for the new version

Done!

**Review by baywet — APPROVED** [review]

**Pull request merged**
