### PR TITLE
Align OTEL http attributes with latest standard

### LINKED ISSUE #120: http - align OTEL http attributes with latest standard
to maintain compatibility with external tooling we should make sure our attribute respect the latest (stable) semantic conventions. When we initially implemented things, the spec was still in draft. The following attributes need to be renamed in the middleware handlers and in the request adapter:
htttp.status_code => http.response.status_code
http.response_content_length => http.response.body.size
http.request_content_length => http.request.body.size
http.flavor => network.protocol.version
http.response_content_type => http.response.header.content-type
http.request_content_type => http.request.header.content-type
http.method => http.request.method
http.host => url.scheme
http.scheme => server.address
http.uri => url.full
http.uri_template => url.uri_template

link to the spec for more information https://opentelemetry.io/docs/specs/semconv/attributes-registry/http/
related https://github.com/microsoftgraph/msgraph-sdk-design/pull/108

### PR DESCRIPTION
**Pull request by ev-gor**
Closes #120

### CODE REVIEW

**Comment by ev-gor** [comment]
@microsoft-github-policy-service agree

**Review by baywet — COMMENTED** [review]
Thanks for the contribution!
I'd encourage you to check in the retry handler which most likely has some of those headers as well.

**Comment by ev-gor** [comment]
I've searched the whole project for attributes listed in #121 and replaced them all. Retry handler has retry_count attribute mentioned in #119, but I wanted to create another PR for it, because I'm not sure about implementation of retry_delay attribute. "int duration in seconds before the request was retried" Does it mean number of seconds between every retry or total sum for all retries?

**Comment by baywet** [comment]
Thank you for the additional information.

The attributes in the retry handler are both outdated AND different from the fullfill/reject implementations...
We'd need to:
1. move them to a constant to avoid repetition
2. update them

The areas I could find
https://github.com/microsoft/kiota-http-guzzle-php/blob/0fb71b6eb67aece7712462e6207a08666048115e/src/Middleware/RetryHandler.php#L161
https://github.com/microsoft/kiota-http-guzzle-php/blob/0fb71b6eb67aece7712462e6207a08666048115e/src/Middleware/RetryHandler.php#L117

And to answer your question: retry delay I think it the delay of each retry (not the total delay).

Let us know if you have any additional comments or questions.

**Comment by baywet** [comment]
also the status code attribute is missing in this handler.

**Comment by ev-gor** [comment]
I added second commit to update resend_count and resend_delay attributes and add status_code attribute in RetryHandler class. If everything is ok, it closes #119

**Review by baywet — COMMENTED** [review]
Thank you for making the changes!
Can you add a new [changelog entry](https://github.com/microsoft/kiota-http-guzzle-php/blob/dev/CHANGELOG.md) (patch bump, today's date, changed) please?
As well as align the [version constant](https://github.com/microsoft/kiota-http-guzzle-php/blob/0fb71b6eb67aece7712462e6207a08666048115e/src/Constants.php#L8)

This will ensure a swift release.

**Comment by ev-gor** [comment]
Done.

**Review by baywet — APPROVED** [review]
Thank you for making the changes!

**Pull request merged**
